# Generated by Django 4.2.1 on 2023-06-05 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='correo')),
                ('user', models.CharField(max_length=255, verbose_name='usuarios')),
                ('contrasena', models.CharField(max_length=20)),
                ('dinero', models.IntegerField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idTransaccion')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(max_length=10)),
                ('estado', models.CharField(default='esperando', max_length=32, verbose_name='estado')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
                ('user', models.ForeignKey(default='defaultUser', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='tasks.usuario', verbose_name='usuario')),
            ],
        ),
    ]
