# Generated by Django 4.2.1 on 2023-07-06 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='target',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dinero',
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='datacompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='nrotransaccion',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='nro de transaccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_origen',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo',
            field=models.IntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='usuario'),
        ),
    ]
